apiVersion: v2
name: victoria-metrics-k8s-stack
description: Kubernetes monitoring on VictoriaMetrics stack. Includes VictoriaMetrics Operator, Grafana dashboards, ServiceScrapes and VMRules
type: application
version: 0.18.11
appVersion: v1.96.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.23.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victoriametrics
  - operator
  - monitoring
  - kubernetes
  - observability
  - tsdb
  - metrics
  - metricsql
  - timeseries
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/operator": "true"
  "artifacthub.io/category": "monitoring-logging"
  "artifacthub.io/links": |
    - name: Sources
      url: https://docs.victoriametrics.com/vmgateway.html
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com

dependencies:
  - name: victoria-metrics-operator
    version: "0.27.4"
    condition: victoria-metrics-operator.enabled
  - name: kube-state-metrics
    version: "5.16.0"
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: "4.26.1"
    condition: prometheus-node-exporter.enabled
  - name: grafana
    version: "7.3.0"
    condition: grafana.enabled
  - name: crds
    version: "0.0.0"
    condition: crds.enabled
